# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31074790b1e6b12db7ca9dd416b0cf1ad67cf6608f6325bc52a791d3c1ffc18ff78f033a9976808361f679ff35af06b40f5419ba456d0d7cf310c2abc955ac2c

test:
  secret_key_base: 23a2502d45ebc97f5ff1c4b3d0240b4586fe94d0d271da46bd23a66f0ba942619f5a69318bb74021bbf88547a30269c5b32952bb92b07f7d3ca6981e3ece94b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
